### ISSUE TITLE
Manglende filer i v1.1.18?

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen-program#1]
Bare meg eller mangler det noen filer i siste release `v1.1.18`?

**Comment by olemp** [comment]
Hei @marlowandre,

Hvilke filer tenker du på? Husk at du må installere vanlig Prosjektportalen først.

**Comment by marlowandre** [comment]
Mappene `Bundle` og `css` mangler sammenlignet med forrige release, og fikk dermed en del feilmeldinger når jeg prøvde en installasjon.

Ny release (1.2.0) ser ut til å inneholde disse mappene, så lukker bare denne saken 😄

**Comment by olemp** [comment]
Aha, flott! Nice find 😆
