### ISSUE TITLE
Program portfolio fails if any project URLs contains a space

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#10]
If one of the projects contain a space, the portfolio will show nothing.

e.g. the query
`(ContentTypeId:0x010109010058561f86d956412b9dd7957bbcd67aae0100* Path:https://sharepoint.no/enheter/enhet01/verden OR Path:https://sharepoint.no/enheter/enhet01/fremtidens by)`
will fail since "fremtidens by" contains a space.

Suggest to encode URLs before querying sharepoint.

**Comment by olemp** [comment]
Encode URL or use quotes?

**Comment by tarjeieo** [comment]
quotes is fine, as long as no other unexpected chars can break the query? But since these chars are already used in an URL, they should be fine I guess...

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen-program/commit/3e253781e2eff53b9ba95ded6ea91487de382513 should solve it hamburger-style 🍔
