### ISSUE TITLE
Presentasjon av prosjektstatus i Internet Explorer 11

### ISSUE THREAD

**Issue by martinfy** [Puzzlepart/prosjektportalen-program#12]
Presentasjon av prosjektstatus ("/SitePages/ProgramProjectStatus.aspx") i Internet Explorer blir dratt ut horisontalt, med tilhørende lang horisontal scrollbar.

**Comment by olemp** [comment]
Skal fungere med `v1.2.9` https://github.com/Puzzlepart/prosjektportalen-program/releases/tag/v1.2.9

**Comment by olemp** [comment]
@martinfy rapporter fortsatt problemer etter oppdatering.

**Comment by martinfy** [comment]
Tror årsaken er "display: flex; display: -ms-flexbox;" i ".status-section .status-columns-container .status-elements", linje 697 i pp.main.css . Internet Explorer 11 har dårlig støtte for flexbox: https://caniuse.com/#search=display%3Aflex

**Comment by olemp** [comment]
Det tror jeg du har helt rett i. Nice find! Får nesten "digge litt deepere" for å se på alternative løsninger. Synd at IE alltid skal henge etter 🔨

**Comment by olemp** [comment]
De kan ikke bruke Chrome @martinfy? 😸

**Comment by martinfy** [comment]
Allerede implementert som workaround (og som generell anbefaling), men folk flest bruker IE dessverre...

**Comment by olemp** [comment]
Kan du prøve denne _pp.program.js_ bundelen, og se om den gjør det bedre?

[pp.program.zip](https://github.com/Puzzlepart/prosjektportalen-program/files/2424698/pp.program.zip)

**Comment by olemp** [comment]
Tror dette løser følgende IE 11 bug:

```
In IE10 and IE11, containers with display: flex and flex-direction: column will not properly calculate their flexed childrens' sizes if the container has min-height but no explicit height property. See bug.
```

**Comment by martinfy** [comment]
Nice! Skal teste hos kunde i morgen 👍

**Comment by martinfy** [comment]
Den gjorde susen i IE,@olemp. Bra jobba! Derimot forsvant ikonene på prosjektstatussiden...

**Comment by olemp** [comment]
Det hørtes rart ut! Skjer det konstant?

**Comment by martinfy** [comment]
Update: det fungerer på sluttbrukerklienten, men ikke fra management server. Samme problem i tidligere versjoner av prosjektportalen, så da kan vi anta at det er noe miljøspesifikt her som er årsaken.
