### ISSUE TITLE
Feil under "legg til prosjekt" i program med Internet Explorer 11

### ISSUE THREAD

**Issue by martinfy** [Puzzlepart/prosjektportalen-program#13]
Når jeg legger et prosjekt til et program, kommer følgende feilmelding i konsollet: "Unable to get property 'key' of undefined or null reference, pp.program.js (1,828267)".

**Comment by olemp** [comment]
Skal fungere med `v1.2.9` https://github.com/Puzzlepart/prosjektportalen-program/releases/tag/v1.2.9
