### ISSUE TITLE
-UseWebLogin in install.ps1 does not work properly

### ISSUE THREAD

**Issue by jankarla** [Puzzlepart/prosjektportalen-program#17]
Installing program on  blank site collection:
![image](https://user-images.githubusercontent.com/46448023/51114722-7139e200-1806-11e9-9e25-66c5a392ece5.png)
Etter pålogging 2 faktor med nøkkel starter scriptet. Så kommer ny pålogging. Denne feiler på autentiseringen videre med feilmelding
![image](https://user-images.githubusercontent.com/46448023/51114841-cece2e80-1806-11e9-8bb6-4dc786f65b14.png)

**Comment by olemp** [comment]
@jankarla Check if this works for you: https://github.com/Puzzlepart/prosjektportalen-program/releases/tag/v1.3.2
