### ISSUE TITLE
Installing emty site collection from program install.ps1 fails on taxonomy field

### ISSUE THREAD

**Issue by jankarla** [Puzzlepart/prosjektportalen-program#18]
![image](https://user-images.githubusercontent.com/46448023/51118249-2f159e00-1810-11e9-8bb5-f0c876a4a72d.png)
Fails on id:  3a0ae560-bd55-45d4-907f-5119bf0a83bb Taxonomy field

**Comment by olemp** [comment]
This is `GtResourceRole` which requires term set `Rolle` with ID `{54da9f47-c64e-4a26-80f3-4d3c3fa1b7b2}`.

Install PP taxonomy and you'll be fine!

**Comment by olemp** [comment]
You'll find `taxonomy-1044` under the folder `templates` in the project portal release folder. Apply it using Apply-PnPProvisioningTemplate.

**Comment by tarjeieo** [comment]
Except you'll also get all the default metadata and possibly losing your modifications of all term sets. 

I would recommend either
(1) Upgrading an existing PP installation to latest, or
(2) Apply the template pre-taxonomyroletermset-1044.pnp located in @upgrade\2.2_2.3\
