### ISSUE TITLE
Cannot read property 'forceUpdate' of undefined

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#19]
Samme feil to steder etter å ha oppgradert pakker til å matche 2.4.0 av Prosjektportalen. Det skjer når en trykker "Synkroniser prosjektdatoer for alle prosjekter" og når en legger til et prosjekt og trykker "legg til".

Ser at vi kaller f.eks. this.projectsDetailsListRef.forceUpdate(); og dette har nok endret seg i ouifabric i en oppgradering, siden feilen er 
`exception = TypeError: Cannot read property 'forceUpdate' of undefined at ProgramProjectsTimelineSync._callee5$ (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:67351:67) at tryCatch (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:45741:40) at Generator.invoke [as _invoke] (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:45975:22) at Generator.prototype.(anonymous function) [as next] (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:45793:21) at https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:66880:71 at new Promise (<anonymous>) at __awaiter (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:66860:12) at ProgramProjectsTimelineSync.syncAllToProjectsTimeline (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:67345:20) at BaseButton._this._onClick (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:18396:33) at HTMLUnknownElement.callCallback (https://tarjeieo.sharepoint.com/sites/prog01/siteassets/pp/js/pp.program.js?v=1.3.2.000ed846:48907:14)`

**Comment by olemp** [comment]
First of all it seems like `yargs` and `stylus` was removed? Gulp didn't run and these packages needed to be-re-added.

**Comment by olemp** [comment]
Seems like `office-ui-fabric-react@lts` works fine. Testing now.
