### ISSUE TITLE
Legge til prosjekt

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen-program#2]
Forslag til forbedring av `Legge til prosjekt`:

Når man skal legge til et prosjekt i et program, dukker det ingen prosjekter opp før man begynner å søke (ser ut som 3 tegn er nødvendig før man får resultat). Det står også _"Ingen prosjekter funnet. Visningen bruker søk, så det kan ta noen minutter fra prosjekter er lagt til eller oppdatert til de vises her."_

Synes dette er litt misvisende. Hva med å vise prosjektene her på samme måte som Porteføljeområdet?

Lurer også på hvor man oppretter et nytt prosjekt? Bare jeg som er blind? 😄 
Jeg finner kun `Opprett nytt program` som er på Porteføljeområdet.

Portalversjon: 2.1.60
Programversjon: 1.2.0

**Comment by olemp** [comment]
God forslag @marlowandre. Det er noe vi har tenkt på selv også, men ikke hatt tid til å legge inn enda. 

`Opprett nytt prosjekt` er det ikke mulighet for. Tanken er at at man bruker en standard PP-installasjon til å lage prosjekter. 🔨

**Comment by marlowandre** [comment]
Aha, var ikke klar over at det søket søker på tvers av siter.

Så hvis jeg forstår deg riktig er tanken å ha denne Programutvidelsen ved siden av en Prosjektportal, og ikke erstatte den opprinnelige installasjonen?

**Comment by olemp** [comment]
Hei igjen @marlowandre,

Ja, det var grunntanken. 💯

**Comment by olemp** [comment]
Den søker over alle siter. Enkelte brukere av Prosjektportalen har 5+ ulike områdesamlinger med Prosjektprotalen installert. 🍔

**Comment by marlowandre** [comment]
Da er jeg med 😄 
Takker! 👍
