### ISSUE TITLE
Issue when clicking "add project" with IE11 in 1.4.0

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#20]
Nothing happens... Error"unable to get property key of undefined or null"

Some polyfill thing missing?

**Comment by olemp** [comment]
Looks like we have completely different environments. I tried to import `@pnp/polyfill-ie11`, updating the JS using gulp `watchProd`, but the dist doesn't load - just an infinite spin. Not sure what to do.

**Comment by olemp** [comment]
Something happend after updating all the packages.

**Comment by tarjeieo** [comment]
Yup, I got issues with gulp watch as well after the recent updates. gulp packageCodeMinify and manual upload works.
