### ISSUE TITLE
Allow project portfolio configuration of portfolio overview in programs

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#26]
Today, the portfolio overview in programs is set, with no way to customize fields, filters, etc.

To implement this, we should create duplicate lists of the project portfolio lists at the root level, and let superusers configure these lists via site settings links. 

Similar to how we solved Portfolio Insights.

**Comment by olemp** [comment]
We need to dynamically add the Path: queries to the query template. How should we do this @tarjeieo?

An alternative is to set the queries like this: {0} ProjectOwner:Tarjei and replace {0} using string.format

**Comment by tarjeieo** [comment]
What about always appending the Path: queries? So the query of the entries should be blank or using a query-filter.

**Comment by olemp** [comment]
Even better @tarjeieo. Let's go for that.
