### ISSUE TITLE
Prosjektstatus - Duplikater

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen-program#3]
Hei. Har oppdaget dulikater i prosjektstatus, Fremdrift, Økonomi, Kvalitet osv. Legger ved et bilde på bunnen.

I en helt ny portal er det to duplikater. Her installerte jeg først Prosjektportalen, og deretter Program.
I et annet miljø hvor jeg oppgraderete Program fra 1.1.16 til 1.2.0 er det tre duplikater. (Oppgraderte forresten ved å kjøre Install.ps1, fant ingen Upgrade.ps1)

Mistenker at installasjonen av Program legger på duplikater i prosjektstatus.

![image](https://user-images.githubusercontent.com/29536394/36717487-89096866-1b9e-11e8-853a-e2fcef737ad6.png)

**Comment by olemp** [comment]
Det er ikke alt som har blitt dokumentert 100% enda.

Kjører du Install.ps1 for `prosjektportalen-program` med parameter `ProjectPortalReleasePath`, vil den installere `prosjektportalen` uten config.

```powershell
.\Install.ps1 -Url $Url -CurrentCredentials -SkipData -SkipTaxonomy -SkipDefaultConfig -SkipLoadingBundle:$SkipLoadingBundle -Environment:$Environment
```

Du kan fjerne duplikatene manuelt fra listen. Lists/StatusSections/AllItems.aspx.

**Comment by olemp** [comment]
Altså, som eksempel 2 her: https://github.com/Puzzlepart/prosjektportalen-program/wiki/Installation

**Comment by marlowandre** [comment]
Jeg installerte i to operasjoner. Først `prosjektportalen` (kun med -SkipTaxonomy), deretter `prosjektportalen-program`
Har ikke testet eksempel 2 enda - dette er den anbefalte installasjonsmetoden?

Slette duplikatene manuelt fungerte 👍 

Har skjønnt at ikke alt er dokumentert enda. Melder bare i fra om det jeg finner 😃 Gi beskjed hvis det blir for mye mas 😄

**Comment by olemp** [comment]
Det er bare fint at du finner mangler @marlowandre. Vi skal oppdatere README med anbefalt "installasjonsmetode" - som er eksempel 2.
