### ISSUE TITLE
Program portfolio at program level: "Add new portfolio view" creates portfolio view in wrong list

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#33]
Program portfolio at program level: "Add new portfolio view" creates portfolio view in wrong list. The new view is only available at portfolio level.

![image](https://user-images.githubusercontent.com/1837390/58044737-d13bee80-7b40-11e9-9139-e5ee98875bfa.png)

In addition, the "Search query" field should not be mandatory at this level, since we're always appending program's projects as filter.

**Comment by tarjeieo** [comment]
Line 254 at src\js\WebParts\DynamicPortfolio\index.tsx needs to use an input param so we can override this from the program-solution: `url: `${_spPageContextInfo.siteAbsoluteUrl}/Lists/DynamicPortfolioViews/NewForm.aspx`,`

**Comment by olemp** [comment]
https://github.com/Puzzlepart/prosjektportalen-program/releases/tag/v1.5.2
