### ISSUE TITLE
Problem loading ProgramPortfolio due to project not having an URL

### ISSUE THREAD

**Issue by Remi749** [Puzzlepart/prosjektportalen-program#38]
There is an issue with the ProgramPortfolio page not showing anything because a project doesn't have an URL it seems.

Image of the error and the program's projects

![image](https://user-images.githubusercontent.com/28678468/65248944-55a07d00-daf3-11e9-8420-f2428f4e2ef1.png)

![image](https://user-images.githubusercontent.com/28678468/65248989-66e98980-daf3-11e9-8a17-783ccf45912f.png)
![image](https://user-images.githubusercontent.com/28678468/65249001-71a41e80-daf3-11e9-938b-5aa07151e53e.png)

The one just above the project without URL-adress (and title) doesn't seem to work and gives a 404.

Implement something that makes the ProgramPortfolio still display even if projects has problems, maybe mark them somehow?

**Comment by olemp** [comment]
@Remi749 Check getStoredProjectsListContext here: https://github.com/Puzzlepart/prosjektportalen-program/blob/master/src/js/%40Common/index.tsx
