### ISSUE TITLE
Field pointing to wrong list ("Project delivereries" instead of "Program deliveries")

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#4]
See https://puzzlepart.atlassian.net/projects/ASSIST/queues/custom/60/ASSIST-1718.

Looks like the 'GtProjectTaskProduct' field on the task list is pointing to the wrong list. It's not overriden as a program extensions.

**Comment by olemp** [comment]
We have not overiden the field. Needs changes to pnp-js-provisioning. 

Looks like lookup fields can't be updated (can't update attribute `List`), so we'll need to delete the existing field first.

https://github.com/Puzzlepart/pnp-js-provisioning/issues/4

**Comment by olemp** [comment]
Solved. Requires minimum `v.2.1.65` of https://github.com/Puzzlepart/prosjektportalen.
