### ISSUE TITLE
Program portfolio overview not working

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen-program#44]
Thank you for reporting an issue. We appreciate your feedback - to help the team understand your needs, please complete the below template to ensure we have the details to help. Thanks!

#### Environment

[x] SharePoint Online

[ ] SharePoint 2013

[ ] SharePoint 2016

#### Browser

[x] Chrome

[ ] Internet Explorer

[ ] Edge

[ ] Safari

[ ] Other

#### Version

Please specify what version you are using: [ 2.6.10 and latest dev of program]

#### Summary

After upgrade to latest PP and React, something is not working here: https://pzlcloud.sharepoint.com/sites/pp-program/ny-kommune-2020/SitePages/Programportefolje.aspx

**Comment by olemp** [comment]
Fixed in https://github.com/Puzzlepart/prosjektportalen-program/pull/45
