### ISSUE TITLE
Forslag: Mulighet for å se Prosjektloggene til prosjekter i programmet

### ISSUE THREAD

**Issue by marlowandre** [Puzzlepart/prosjektportalen-program#7]
Har et forslag om å synliggjøre Prosjektlogg i programmet som prosjektene er medlem av. Kanskje i likhet med hvordan Program-gevinsoversikt fungerer?

**Comment by olemp** [comment]
Hei @marlowandre!

Større utviklingsoppgaver som dette trenger vi kundefinansiering for å gjennomføre. Ta kontakt med oss om du har noen ledetråder her.

**Comment by tarjeieo** [comment]
Implementert i kommende versjon
